name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j4
          ./bench > output.txt
      - uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark
          tool: 'catch2'
          output-file-path: build/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: benchmarks