name: benchmark
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
          ninja
          bench > output.txt
      - uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark
          tool: 'catch2'
          output-file-path: build/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true